module amba_top_wrapper (
    // --- Interface: s00_axi (AXI4 SLAVE) ---
    input  wire              aclk,
    input  wire              aresetn,
    input  wire  [ID_W-1:0]  s00_axi_awid,
    input  wire  [31:0]      s00_axi_awaddr,
    input  wire  [7:0]       s00_axi_awlen,
    input  wire  [2:0]       s00_axi_awsize,
    input  wire  [1:0]       s00_axi_awburst,
    input  wire              s00_axi_awlock,
    input  wire  [3:0]       s00_axi_awcache,
    input  wire  [2:0]       s00_axi_awprot,
    input  wire  [3:0]       s00_axi_awqos,
    input  wire  [3:0]       s00_axi_awregion,
    input  wire  [USER_W-1:0]s00_axi_awuser,
    input  wire              s00_axi_awvalid,
    output wire              s00_axi_awready,
    input  wire  [31:0]      s00_axi_wdata,
    input  wire  [3:0]       s00_axi_wstrb,
    input  wire              s00_axi_wlast,
    input  wire  [USER_W-1:0]s00_axi_wuser,
    input  wire              s00_axi_wvalid,
    output wire              s00_axi_wready,
    output wire  [ID_W-1:0]  s00_axi_bid,
    output wire  [1:0]       s00_axi_bresp,
    output wire  [USER_W-1:0]s00_axi_buser,
    output wire              s00_axi_bvalid,
    input  wire              s00_axi_bready,
    input  wire  [ID_W-1:0]  s00_axi_arid,
    input  wire  [31:0]      s00_axi_araddr,
    input  wire  [7:0]       s00_axi_arlen,
    input  wire  [2:0]       s00_axi_arsize,
    input  wire  [1:0]       s00_axi_arburst,
    input  wire              s00_axi_arlock,
    input  wire  [3:0]       s00_axi_arcache,
    input  wire  [2:0]       s00_axi_arprot,
    input  wire  [3:0]       s00_axi_arqos,
    input  wire  [3:0]       s00_axi_arregion,
    input  wire  [USER_W-1:0]s00_axi_aruser,
    input  wire              s00_axi_arvalid,
    output wire              s00_axi_arready,
    output wire  [ID_W-1:0]  s00_axi_rid,
    output wire  [31:0]      s00_axi_rdata,
    output wire  [1:0]       s00_axi_rresp,
    output wire              s00_axi_rlast,
    output wire  [USER_W-1:0]s00_axi_ruser,
    output wire              s00_axi_rvalid,
    input  wire              s00_axi_rready,
    // --- Interface: m00_axi (AXI4 MASTER) ---
    output wire  [ID_W-1:0]  m00_axi_awid,
    output wire  [63:0]      m00_axi_awaddr,
    output wire  [7:0]       m00_axi_awlen,
    output wire  [2:0]       m00_axi_awsize,
    output wire  [1:0]       m00_axi_awburst,
    output wire              m00_axi_awlock,
    output wire  [3:0]       m00_axi_awcache,
    output wire  [2:0]       m00_axi_awprot,
    output wire  [3:0]       m00_axi_awqos,
    output wire  [3:0]       m00_axi_awregion,
    output wire  [USER_W-1:0]m00_axi_awuser,
    output wire              m00_axi_awvalid,
    input  wire              m00_axi_awready,
    output wire  [127:0]     m00_axi_wdata,
    output wire  [15:0]      m00_axi_wstrb,
    output wire              m00_axi_wlast,
    output wire  [USER_W-1:0]m00_axi_wuser,
    output wire              m00_axi_wvalid,
    input  wire              m00_axi_wready,
    input  wire  [ID_W-1:0]  m00_axi_bid,
    input  wire  [1:0]       m00_axi_bresp,
    input  wire  [USER_W-1:0]m00_axi_buser,
    input  wire              m00_axi_bvalid,
    output wire              m00_axi_bready,
    output wire  [ID_W-1:0]  m00_axi_arid,
    output wire  [63:0]      m00_axi_araddr,
    output wire  [7:0]       m00_axi_arlen,
    output wire  [2:0]       m00_axi_arsize,
    output wire  [1:0]       m00_axi_arburst,
    output wire              m00_axi_arlock,
    output wire  [3:0]       m00_axi_arcache,
    output wire  [2:0]       m00_axi_arprot,
    output wire  [3:0]       m00_axi_arqos,
    output wire  [3:0]       m00_axi_arregion,
    output wire  [USER_W-1:0]m00_axi_aruser,
    output wire              m00_axi_arvalid,
    input  wire              m00_axi_arready,
    input  wire  [ID_W-1:0]  m00_axi_rid,
    input  wire  [127:0]     m00_axi_rdata,
    input  wire  [1:0]       m00_axi_rresp,
    input  wire              m00_axi_rlast,
    input  wire  [USER_W-1:0]m00_axi_ruser,
    input  wire              m00_axi_rvalid,
    output wire              m00_axi_rready,
    // --- Interface: p00_apb (APB MASTER) ---
    input  wire              pclk,
    input  wire              presetn,
    output wire  [11:0]      p00_apb_paddr,
    output wire  [2:0]       p00_apb_pprot,
    output wire              p00_apb_psel,
    output wire              p00_apb_penable,
    output wire              p00_apb_pwrite,
    output wire  [31:0]      p00_apb_pwdata,
    input  wire  [31:0]      p00_apb_prdata,
    input  wire              p00_apb_pready
);

endmodule