from __future__ import annotations

from pathlib import Path

from .models import FieldModel, ModuleModel, RegisterModel
from .reg_common import clog2, write_text


def generate_rtl(module: ModuleModel, out_dir: str) -> list[Path]:
    output = Path(out_dir)
    plus = output / "plus"
    output.mkdir(parents=True, exist_ok=True)
    plus.mkdir(parents=True, exist_ok=True)
    generated: list[Path] = []
    seen: set[str] = set()
    for item, _, _ in module.walk():
        source = str(Path(item.source_path).resolve()).lower()
        if source in seen:
            continue
        seen.add(source)
        main_path = output / f"{item.name}.sv"
        typedef_path = plus / f"{item.name}_typedef.sv"
        wrapper_path = plus / f"{item.name}_wrap.sv"
        template_path = plus / f"tmp_{item.name}.sv"
        write_text(main_path, _main_rtl(item))
        write_text(typedef_path, _typedef_rtl(item))
        write_text(wrapper_path, _wrapper_rtl(item))
        write_text(template_path, _integration_template(item))
        generated.extend([main_path, typedef_path, wrapper_path, template_path])
    return generated


def _main_rtl(module: ModuleModel) -> str:
    ports = _main_ports(module)
    targets = _targets(module)
    deep_shadow = _deep_shadow(module)
    shallow_shadow = any(reg.special.shadow == 1 for reg in module.registers)
    lines = [
        "// Generated by csr_tool. Do not edit manually.",
        f"module {module.name} #(",
        "    parameter integer CSR_AW = 32,",
        f"    parameter integer CSR_DW = {module.base_info.reg_bitwidth}",
        ")",
        "(",
        *_format_ports(ports),
        ");",
        "",
        "//localparam-----------------------------------------------------------------",
        "localparam integer CSR_REQ_OSD_NUM = 256;",
        "localparam integer OTF_CNT_W = $clog2(CSR_REQ_OSD_NUM);",
        f"localparam integer TARGET_SEL_W = {clog2(len(targets) + 1)};",
        "localparam [TARGET_SEL_W-1:0] TARGET_LOCAL = 'd0;",
    ]
    for index, reg in enumerate(targets, start=1):
        lines.append(
            f"localparam [TARGET_SEL_W-1:0] TARGET_{reg.name.upper()} = 'd{index};"
        )
    if deep_shadow:
        lines.extend([
            f"localparam integer SHADOW_DEPTH = {deep_shadow};",
            "localparam integer SHADOW_IDX_W = $clog2(SHADOW_DEPTH);",
        ])

    lines.extend([
        "",
        "//signal declare-------------------------------------------------------------",
        "reg  [CSR_DW-1:0] w_csr_wmask;",
        "reg  [CSR_DW-1:0] w_local_rdata;",
        "reg  [TARGET_SEL_W-1:0] w_req_target;",
        "reg  [CSR_DW-1:0] w_rsp_rdata;",
        "reg  w_rsp_rvalid;",
        "reg  [CSR_DW-1:0] r_local_rsp_rdata;",
        "reg  r_local_rsp_rvalid;",
        "reg  [TARGET_SEL_W-1:0] r_read_target;",
        "reg  [OTF_CNT_W-1:0] r_otf_cnt;",
        "wire b_req_is_read;",
        "wire b_target_switch_block;",
        "wire b_req_accept;",
        "wire b_read_accept;",
        "wire b_rsp_accept;",
        "wire b_local_read_accept;",
        "integer byte_idx;",
    ])
    lines.extend(_register_declarations(module))
    if deep_shadow:
        lines.extend([
            "reg  [SHADOW_IDX_W-1:0] r_shadow_wr_idx;",
            "reg  [SHADOW_IDX_W-1:0] r_shadow_rd_idx;",
            "reg  [SHADOW_IDX_W:0] r_shadow_count;",
            "wire b_shadow_push;",
            "wire b_shadow_pop;",
        ])

    lines.extend([
        "",
        "//body-----------------------------------------------------------------------",
        "//output assign---",
        "assign b_req_is_read = i_csr_req_valid && !i_csr_req_write;",
        "assign b_target_switch_block = b_req_is_read && (r_otf_cnt != '0) &&",
        "                               (w_req_target != r_read_target);",
        "assign b_req_accept = i_csr_req_valid && o_csr_req_ready;",
        "assign b_read_accept = b_req_accept && !i_csr_req_write;",
        "assign b_rsp_accept = w_rsp_rvalid;",
        "assign b_local_read_accept = b_read_accept &&",
        "                             (w_req_target == TARGET_LOCAL);",
        "assign o_csr_rsp_rdata = w_rsp_rdata;",
        "assign o_csr_rsp_rvalid = w_rsp_rvalid;",
    ])
    lines.extend(_field_output_assigns(module))
    if deep_shadow:
        lines.extend([
            "assign b_shadow_push = i_pulse_shadow_upen &&",
            "                       (r_shadow_count < SHADOW_DEPTH);",
            "assign b_shadow_pop = i_pulse_shadow_rden &&",
            "                      (r_shadow_count != '0);",
            "assign o_dbg_shadow_wr_idx = r_shadow_wr_idx;",
            "assign o_dbg_shadow_rd_idx = r_shadow_rd_idx;",
            "assign o_dbg_shadow_water_level = SHADOW_DEPTH - r_shadow_count;",
            "assign o_pulse_err_write_when_full = i_pulse_shadow_upen &&",
            "                                          (r_shadow_count == SHADOW_DEPTH);",
            "assign o_pulse_err_read_when_empty = i_pulse_shadow_rden &&",
            "                                         (r_shadow_count == '0);",
        ])
    lines.extend(_target_output_assigns(module))

    lines.extend([
        "",
        "//statement----",
        "always @* begin",
        "    w_csr_wmask = '0;",
        "    for (byte_idx = 0; byte_idx < (CSR_DW / 8); byte_idx = byte_idx + 1) begin",
        "        w_csr_wmask[byte_idx*8 +: 8] = {8{i_csr_req_wstrb[byte_idx]}};",
        "    end",
        "end",
        "",
        "always @* begin",
        "    w_req_target = TARGET_LOCAL;",
    ])
    for reg in targets:
        lines.extend([
            f"    if ((i_csr_req_addr >= CSR_AW'(32'h{reg.offset:08X})) &&",
            f"        (i_csr_req_addr < CSR_AW'(32'h{reg.offset + (reg.special.bytesize or 0):08X})))",
            f"        w_req_target = TARGET_{reg.name.upper()};",
        ])
    lines.extend([
        "end",
        "",
        "always @* begin",
        "    if (b_target_switch_block)",
        "        o_csr_req_ready = 1'b0;",
        "    else begin",
        "        case (w_req_target)",
        "            TARGET_LOCAL: o_csr_req_ready = 1'b1;",
    ])
    for index, reg in enumerate(targets):
        lines.append(
            f"            TARGET_{reg.name.upper()}: "
            f"o_csr_req_ready = i_tx_csr_req_ready[{index}];"
        )
    lines.extend([
        "            default: o_csr_req_ready = 1'b0;",
        "        endcase",
        "    end",
        "end",
        "",
        "always @* begin",
        "    w_rsp_rdata = r_local_rsp_rdata;",
        "    w_rsp_rvalid = r_local_rsp_rvalid;",
        "    case (r_read_target)",
        "        TARGET_LOCAL: begin",
        "            w_rsp_rdata = r_local_rsp_rdata;",
        "            w_rsp_rvalid = r_local_rsp_rvalid;",
        "        end",
    ])
    for index, reg in enumerate(targets):
        lines.extend([
            f"        TARGET_{reg.name.upper()}: begin",
            f"            w_rsp_rdata = i_tx_csr_rsp_rdata[{index}];",
            f"            w_rsp_rvalid = i_tx_csr_rsp_rvalid[{index}];",
            "        end",
        ])
    lines.extend([
        "        default: begin",
        "            w_rsp_rdata = '0;",
        "            w_rsp_rvalid = 1'b0;",
        "        end",
        "    endcase",
        "end",
        "",
        "always @* begin",
        "    w_local_rdata = '0;",
    ])
    lines.extend(_read_decode(module))
    lines.extend([
        "end",
        "",
        "always @(posedge clk or negedge rst_n) begin",
        "    if (!rst_n) begin",
        "        r_local_rsp_rdata <= '0;",
        "        r_local_rsp_rvalid <= 1'b0;",
        "    end",
        "    else begin",
        "        r_local_rsp_rvalid <= b_local_read_accept;",
        "        if (b_local_read_accept)",
        "            r_local_rsp_rdata <= w_local_rdata;",
        "    end",
        "end",
        "",
        "always @(posedge clk or negedge rst_n) begin",
        "    if (!rst_n) begin",
        "        r_read_target <= TARGET_LOCAL;",
        "        r_otf_cnt <= '0;",
        "    end",
        "    else begin",
        "        if (b_read_accept && (r_otf_cnt == '0))",
        "            r_read_target <= w_req_target;",
        "        case ({b_read_accept, b_rsp_accept})",
        "            2'b10: r_otf_cnt <= r_otf_cnt + 1'b1;",
        "            2'b01: r_otf_cnt <= r_otf_cnt - 1'b1;",
        "            default: r_otf_cnt <= r_otf_cnt;",
        "        endcase",
        "    end",
        "end",
    ])
    lines.extend(_register_statements(module))
    if deep_shadow:
        lines.extend(_shadow_control())
    lines.extend([
        "",
        "//instance----",
        "// No submodule instances are required.",
        "",
        "endmodule",
    ])
    return "\n".join(lines)


def _main_ports(module: ModuleModel) -> list[str]:
    ports = [
        "input  wire                     clk",
        "input  wire                     rst_n",
        "",
        "input  wire                     i_csr_req_write",
        "input  wire [CSR_AW-1:0]        i_csr_req_addr",
        "input  wire [CSR_DW-1:0]        i_csr_req_wdata",
        "input  wire [CSR_DW/8-1:0]      i_csr_req_wstrb",
        "input  wire                     i_csr_req_valid",
        "output reg                      o_csr_req_ready",
        "output wire [CSR_DW-1:0]        o_csr_rsp_rdata",
        "output wire                     o_csr_rsp_rvalid",
    ]
    for reg in module.registers:
        for field in reg.fields:
            width = _port_width(reg, field)
            if reg.reg_type == "cfg":
                ports.append(f"output wire {width:<20} o_cfg_{reg.name}_{field.name}")
            elif reg.reg_type == "status":
                ports.append(f"input  wire {width:<20} i_sta_{reg.name}_{field.name}")
            elif reg.reg_type == "cmd":
                ports.append(f"output wire {width:<20} o_cmd_{reg.name}_{field.name}")
            elif reg.reg_type == "irq":
                ports.append(f"input  wire {width:<20} i_irqsta_{reg.name}_{field.name}")
                ports.append(f"output wire {width:<20} o_irqclr_{reg.name}_{field.name}")
    if any(reg.special.shadow for reg in module.registers):
        ports.append("input  wire                     i_pulse_shadow_upen")
    deep = _deep_shadow(module)
    if deep:
        idx_width = clog2(deep)
        level_width = clog2(deep + 1)
        ports.extend([
            "input  wire                     i_pulse_shadow_rden",
            f"output wire [{idx_width - 1}:0]             o_dbg_shadow_wr_idx",
            f"output wire [{idx_width - 1}:0]             o_dbg_shadow_rd_idx",
            f"output wire [{level_width - 1}:0]             o_dbg_shadow_water_level",
            "output wire                     o_pulse_err_write_when_full",
            "output wire                     o_pulse_err_read_when_empty",
        ])
    target_count = len(_targets(module))
    if target_count:
        ports.extend([
            "",
            f"output wire [{target_count - 1}:0]             o_tx_csr_req_write",
            f"output wire [{target_count - 1}:0][CSR_AW-1:0] o_tx_csr_req_addr",
            f"output wire [{target_count - 1}:0][CSR_DW-1:0] o_tx_csr_req_wdata",
            f"output wire [{target_count - 1}:0][CSR_DW/8-1:0] o_tx_csr_req_wstrb",
            f"output wire [{target_count - 1}:0]             o_tx_csr_req_valid",
            f"input  wire [{target_count - 1}:0]             i_tx_csr_req_ready",
            f"input  wire [{target_count - 1}:0][CSR_DW-1:0] i_tx_csr_rsp_rdata",
            f"input  wire [{target_count - 1}:0]             i_tx_csr_rsp_rvalid",
        ])
    return ports


def _format_ports(ports: list[str]) -> list[str]:
    records: dict[int, tuple[str, str, str, str]] = {}
    for index, item in enumerate(ports):
        if not item:
            continue
        tokens = item.split()
        if len(tokens) < 3:
            raise ValueError(f"Invalid port declaration: {item}")
        direction = tokens[0]
        net_type = tokens[1]
        signal_name = tokens[-1]
        data_type = " ".join(tokens[2:-1])
        records[index] = (direction, net_type, data_type, signal_name)

    direction_width = max(len(item[0]) for item in records.values())
    net_type_width = max(len(item[1]) for item in records.values())
    data_type_width = max(len(item[2]) for item in records.values())
    signal_name_width = max(len(item[3]) for item in records.values())
    last = max(records)
    formatted: list[str] = []
    for index, item in enumerate(ports):
        if not item:
            formatted.append("")
            continue
        direction, net_type, data_type, signal_name = records[index]
        declaration = (
            f"    {direction:<{direction_width}} "
            f"{net_type:<{net_type_width}} "
            f"{data_type:<{data_type_width}} "
            f"{signal_name:<{signal_name_width}} "
        )
        formatted.append(declaration + ("," if index != last else "//,"))
    return formatted


def _port_width(reg: RegisterModel, field: FieldModel) -> str:
    dimensions = []
    if reg.repeat > 1:
        dimensions.append(f"[{reg.repeat - 1}:0]")
    if field.width > 1:
        dimensions.append(f"[{field.width - 1}:0]")
    return "".join(dimensions)


def _register_declarations(module: ModuleModel) -> list[str]:
    lines: list[str] = []
    for reg in module.registers:
        for field in reg.fields:
            dims = _packed_dims(reg.repeat, field.width)
            tag = f"{reg.name}_{field.name}"
            if reg.reg_type in {"cfg", "cmd"}:
                if reg.special.shadow >= 2:
                    lines.append(
                        f"reg  [SHADOW_DEPTH-1:0]{dims} r_{tag};"
                    )
                    lines.append(f"reg  {dims} r_shd_{tag};")
                elif reg.special.shadow == 1:
                    lines.append(f"reg  {dims} r_{tag};")
                    lines.append(f"reg  {dims} r_shd_{tag};")
                else:
                    lines.append(f"reg  {dims} r_{tag};")
    return lines


def _packed_dims(repeat: int, width: int) -> str:
    result = ""
    if repeat > 1:
        result += f"[{repeat - 1}:0]"
    if width > 1:
        result += f"[{width - 1}:0]"
    return result


def _field_output_assigns(module: ModuleModel) -> list[str]:
    lines: list[str] = []
    for reg in module.registers:
        for field in reg.fields:
            tag = f"{reg.name}_{field.name}"
            if reg.reg_type == "cfg":
                source = f"r_{tag}"
                if reg.special.shadow >= 2:
                    source += "[r_shadow_rd_idx]"
                lines.append(f"assign o_cfg_{tag} = {source};")
            elif reg.reg_type == "cmd":
                lines.append(f"assign o_cmd_{tag} = r_{tag};")
            elif reg.reg_type == "irq":
                if reg.repeat == 1:
                    expression = (
                        f"(b_req_accept && i_csr_req_write && "
                        f"(w_req_target == TARGET_LOCAL) && "
                        f"(i_csr_req_addr == CSR_AW'(32'h{reg.offset:08X}))) ? "
                        f"(i_csr_req_wdata[{field.msb}:{field.lsb}] & "
                        f"w_csr_wmask[{field.msb}:{field.lsb}]) : '0"
                    )
                    lines.append(f"assign o_irqclr_{tag} = {expression};")
                else:
                    for index in range(reg.repeat):
                        offset = reg.offset + index * module.word_bytes
                        expression = (
                            f"(b_req_accept && i_csr_req_write && "
                            f"(w_req_target == TARGET_LOCAL) && "
                            f"(i_csr_req_addr == CSR_AW'(32'h{offset:08X}))) ? "
                            f"(i_csr_req_wdata[{field.msb}:{field.lsb}] & "
                            f"w_csr_wmask[{field.msb}:{field.lsb}]) : '0"
                        )
                        lines.append(
                            f"assign o_irqclr_{tag}[{index}] = {expression};"
                        )
    return lines


def _target_output_assigns(module: ModuleModel) -> list[str]:
    lines: list[str] = []
    for index, reg in enumerate(_targets(module)):
        base = reg.offset
        lines.extend([
            f"assign o_tx_csr_req_write[{index}] = i_csr_req_write;",
            f"assign o_tx_csr_req_addr[{index}] = i_csr_req_addr - "
            f"CSR_AW'(32'h{base:08X});",
            f"assign o_tx_csr_req_wdata[{index}] = i_csr_req_wdata;",
            f"assign o_tx_csr_req_wstrb[{index}] = i_csr_req_wstrb;",
            f"assign o_tx_csr_req_valid[{index}] = i_csr_req_valid &&",
            f"                                         !b_target_switch_block &&",
            f"                                         (w_req_target == "
            f"TARGET_{reg.name.upper()});",
        ])
    return lines


def _read_decode(module: ModuleModel) -> list[str]:
    lines: list[str] = []
    for reg in module.registers:
        if reg.reg_type in {"slave", "mem"}:
            continue
        for index in range(reg.repeat):
            offset = reg.offset + index * module.word_bytes
            lines.append(
                f"    if (i_csr_req_addr == CSR_AW'(32'h{offset:08X})) begin"
            )
            for field in reg.fields:
                source = _read_source(reg, field, index)
                lines.append(
                    f"        w_local_rdata[{field.msb}:{field.lsb}] = {source};"
                )
            lines.append("    end")
    return lines


def _read_source(reg: RegisterModel, field: FieldModel, index: int) -> str:
    tag = f"{reg.name}_{field.name}"
    repeat_index = f"[{index}]" if reg.repeat > 1 else ""
    if reg.reg_type == "cfg":
        if reg.special.shadow >= 2:
            return f"r_{tag}[r_shadow_rd_idx]{repeat_index}"
        return f"r_{tag}{repeat_index}"
    if reg.reg_type == "status":
        return f"i_sta_{tag}{repeat_index}"
    if reg.reg_type == "cmd":
        return f"r_{tag}{repeat_index}"
    return f"i_irqsta_{tag}{repeat_index}"


def _register_statements(module: ModuleModel) -> list[str]:
    lines: list[str] = []
    for reg in module.registers:
        if reg.reg_type not in {"cfg", "cmd"}:
            continue
        lines.extend(["", f"// {reg.name} register storage"])
        lines.extend([
            "always @(posedge clk or negedge rst_n) begin",
            "    if (!rst_n) begin",
        ])
        for field in reg.fields:
            tag = f"{reg.name}_{field.name}"
            for index in range(reg.repeat):
                suffix = f"[{index}]" if reg.repeat > 1 else ""
                default = field.default_for(index)
                if reg.special.shadow >= 2:
                    lines.append(f"        r_shd_{tag}{suffix} <= {field.width}'h{default:X};")
                    for depth in range(reg.special.shadow):
                        lines.append(
                            f"        r_{tag}[{depth}]{suffix} <= {field.width}'h{default:X};"
                        )
                elif reg.special.shadow == 1:
                    lines.append(f"        r_shd_{tag}{suffix} <= {field.width}'h{default:X};")
                    lines.append(f"        r_{tag}{suffix} <= {field.width}'h{default:X};")
                else:
                    lines.append(f"        r_{tag}{suffix} <= {field.width}'h{default:X};")
        lines.extend(["    end", "    else begin"])
        for index in range(reg.repeat):
            offset = reg.offset + index * module.word_bytes
            suffix = f"[{index}]" if reg.repeat > 1 else ""
            lines.extend([
                f"        if (b_req_accept && i_csr_req_write &&",
                f"            (w_req_target == TARGET_LOCAL) &&",
                f"            (i_csr_req_addr == CSR_AW'(32'h{offset:08X}))) begin",
            ])
            for field in reg.fields:
                tag = f"{reg.name}_{field.name}"
                target = (
                    f"r_shd_{tag}{suffix}"
                    if reg.special.shadow else f"r_{tag}{suffix}"
                )
                wdata = f"i_csr_req_wdata[{field.msb}:{field.lsb}]"
                wmask = f"w_csr_wmask[{field.msb}:{field.lsb}]"
                if reg.reg_type == "cmd":
                    lines.append(f"            {target} <= {target} ^ ({wdata} & {wmask});")
                else:
                    lines.append(
                        f"            {target} <= ({target} & ~{wmask}) | "
                        f"({wdata} & {wmask});"
                    )
            lines.append("        end")
        if reg.special.shadow == 1:
            lines.append("        if (i_pulse_shadow_upen) begin")
            for field in reg.fields:
                tag = f"{reg.name}_{field.name}"
                lines.append(f"            r_{tag} <= r_shd_{tag};")
            lines.append("        end")
        elif reg.special.shadow >= 2:
            lines.append("        if (b_shadow_push) begin")
            for field in reg.fields:
                tag = f"{reg.name}_{field.name}"
                lines.append(
                    f"            r_{tag}[r_shadow_wr_idx] <= r_shd_{tag};"
                )
            lines.append("        end")
        lines.extend(["    end", "end"])
    return lines


def _shadow_control() -> list[str]:
    return [
        "",
        "// Shared shadow FIFO control",
        "always @(posedge clk or negedge rst_n) begin",
        "    if (!rst_n) begin",
        "        r_shadow_wr_idx <= '0;",
        "        r_shadow_rd_idx <= '0;",
        "        r_shadow_count <= '0;",
        "    end",
        "    else begin",
        "        if (b_shadow_push) begin",
        "            if (r_shadow_wr_idx == SHADOW_DEPTH - 1)",
        "                r_shadow_wr_idx <= '0;",
        "            else",
        "                r_shadow_wr_idx <= r_shadow_wr_idx + 1'b1;",
        "        end",
        "        if (b_shadow_pop) begin",
        "            if (r_shadow_rd_idx == SHADOW_DEPTH - 1)",
        "                r_shadow_rd_idx <= '0;",
        "            else",
        "                r_shadow_rd_idx <= r_shadow_rd_idx + 1'b1;",
        "        end",
        "        case ({b_shadow_push, b_shadow_pop})",
        "            2'b10: r_shadow_count <= r_shadow_count + 1'b1;",
        "            2'b01: r_shadow_count <= r_shadow_count - 1'b1;",
        "            default: r_shadow_count <= r_shadow_count;",
        "        endcase",
        "    end",
        "end",
    ]


def _typedef_rtl(module: ModuleModel) -> str:
    lines = [
        "// Generated packed interface types.",
        f"`ifndef {module.name.upper()}_TYPEDEF_SV",
        f"`define {module.name.upper()}_TYPEDEF_SV",
        "",
    ]
    groups = {
        "cfg": [],
        "status": [],
        "cmd": [],
        "irqsta": [],
        "irqclr": [],
    }
    for reg in module.registers:
        for field in reg.fields:
            dims = _packed_dims(reg.repeat, field.width)
            declaration = f"    logic {dims} {reg.name}_{field.name};"
            if reg.reg_type == "cfg":
                groups["cfg"].append(declaration)
            elif reg.reg_type == "status":
                groups["status"].append(declaration)
            elif reg.reg_type == "cmd":
                groups["cmd"].append(declaration)
            elif reg.reg_type == "irq":
                groups["irqsta"].append(declaration)
                groups["irqclr"].append(declaration)
    for group, declarations in groups.items():
        if not declarations:
            continue
        lines.extend([
            "typedef struct packed {",
            *declarations,
            f"}} {module.name}_{group}_ts;",
            "",
        ])
    lines.extend([f"`endif // {module.name.upper()}_TYPEDEF_SV"])
    return "\n".join(lines)


def _wrapper_rtl(module: ModuleModel) -> str:
    groups = _present_groups(module)
    ports = [
        "input  wire                     clk",
        "input  wire                     rst_n",
        "input  wire                     i_csr_req_write",
        "input  wire [CSR_AW-1:0]        i_csr_req_addr",
        "input  wire [CSR_DW-1:0]        i_csr_req_wdata",
        "input  wire [CSR_DW/8-1:0]      i_csr_req_wstrb",
        "input  wire                     i_csr_req_valid",
        "output wire                     o_csr_req_ready",
        "output wire [CSR_DW-1:0]        o_csr_rsp_rdata",
        "output wire                     o_csr_rsp_rvalid",
    ]
    directions = {
        "cfg": "output wire",
        "status": "input  wire",
        "cmd": "output wire",
        "irqsta": "input  wire",
        "irqclr": "output wire",
    }
    for group in groups:
        ports.append(
            f"{directions[group]} {module.name}_{group}_ts"
            f"     {'o' if group in {'cfg', 'cmd', 'irqclr'} else 'i'}_{group}"
        )
    if any(reg.special.shadow for reg in module.registers):
        ports.append("input  wire                     i_pulse_shadow_upen")
    if _deep_shadow(module):
        ports.extend([
            "input  wire                     i_pulse_shadow_rden",
            f"output wire [{clog2(_deep_shadow(module)) - 1}:0]             o_dbg_shadow_wr_idx",
            f"output wire [{clog2(_deep_shadow(module)) - 1}:0]             o_dbg_shadow_rd_idx",
            f"output wire [{clog2(_deep_shadow(module) + 1) - 1}:0]             o_dbg_shadow_water_level",
            "output wire                     o_pulse_err_write_when_full",
            "output wire                     o_pulse_err_read_when_empty",
        ])
    target_count = len(_targets(module))
    if target_count:
        ports.extend(_main_ports(module)[-8:])

    bindings: list[tuple[str, str, str, str]] = [
        ("clk", "i", "", "clk"),
        ("rst_n", "i", "", "rst_n"),
        ("i_csr_req_write", "i", "", "i_csr_req_write"),
        ("i_csr_req_addr", "i", "[CSR_AW-1:0]", "i_csr_req_addr"),
        ("i_csr_req_wdata", "i", "[CSR_DW-1:0]", "i_csr_req_wdata"),
        ("i_csr_req_wstrb", "i", "[CSR_DW/8-1:0]", "i_csr_req_wstrb"),
        ("i_csr_req_valid", "i", "", "i_csr_req_valid"),
        ("o_csr_req_ready", "o", "", "o_csr_req_ready"),
        ("o_csr_rsp_rdata", "o", "[CSR_DW-1:0]", "o_csr_rsp_rdata"),
        ("o_csr_rsp_rvalid", "o", "", "o_csr_rsp_rvalid"),
    ]
    for reg in module.registers:
        for field in reg.fields:
            tag = f"{reg.name}_{field.name}"
            width = _port_width(reg, field)
            if reg.reg_type == "cfg":
                bindings.append((f"o_cfg_{tag}", "o", width, f"o_cfg.{tag}"))
            elif reg.reg_type == "status":
                bindings.append((f"i_sta_{tag}", "i", width, f"i_status.{tag}"))
            elif reg.reg_type == "cmd":
                bindings.append((f"o_cmd_{tag}", "o", width, f"o_cmd.{tag}"))
            elif reg.reg_type == "irq":
                bindings.append((f"i_irqsta_{tag}", "i", width, f"i_irqsta.{tag}"))
                bindings.append((f"o_irqclr_{tag}", "o", width, f"o_irqclr.{tag}"))
    if any(reg.special.shadow for reg in module.registers):
        bindings.append((
            "i_pulse_shadow_upen", "i", "", "i_pulse_shadow_upen"
        ))
    if _deep_shadow(module):
        depth = _deep_shadow(module)
        bindings.extend([
            ("i_pulse_shadow_rden", "i", "", "i_pulse_shadow_rden"),
            ("o_dbg_shadow_wr_idx", "o", f"[{clog2(depth) - 1}:0]", "o_dbg_shadow_wr_idx"),
            ("o_dbg_shadow_rd_idx", "o", f"[{clog2(depth) - 1}:0]", "o_dbg_shadow_rd_idx"),
            (
                "o_dbg_shadow_water_level",
                "o",
                f"[{clog2(depth + 1) - 1}:0]",
                "o_dbg_shadow_water_level",
            ),
            (
                "o_pulse_err_write_when_full",
                "o",
                "",
                "o_pulse_err_write_when_full",
            ),
            (
                "o_pulse_err_read_when_empty",
                "o",
                "",
                "o_pulse_err_read_when_empty",
            ),
        ])
    if target_count:
        bindings.extend([
            ("o_tx_csr_req_write", "o", f"[{target_count - 1}:0]", "o_tx_csr_req_write"),
            (
                "o_tx_csr_req_addr",
                "o",
                f"[{target_count - 1}:0][CSR_AW-1:0]",
                "o_tx_csr_req_addr",
            ),
            (
                "o_tx_csr_req_wdata",
                "o",
                f"[{target_count - 1}:0][CSR_DW-1:0]",
                "o_tx_csr_req_wdata",
            ),
            (
                "o_tx_csr_req_wstrb",
                "o",
                f"[{target_count - 1}:0][CSR_DW/8-1:0]",
                "o_tx_csr_req_wstrb",
            ),
            ("o_tx_csr_req_valid", "o", f"[{target_count - 1}:0]", "o_tx_csr_req_valid"),
            ("i_tx_csr_req_ready", "i", f"[{target_count - 1}:0]", "i_tx_csr_req_ready"),
            (
                "i_tx_csr_rsp_rdata",
                "i",
                f"[{target_count - 1}:0][CSR_DW-1:0]",
                "i_tx_csr_rsp_rdata",
            ),
            ("i_tx_csr_rsp_rvalid", "i", f"[{target_count - 1}:0]", "i_tx_csr_rsp_rvalid"),
        ])
    declarations = []
    assignments = []
    connections = []
    for port, direction, width, expression in bindings:
        base_name = port[2:] if port.startswith(("i_", "o_")) else port
        wire_name = f"u_csr_{direction}_{base_name}"
        declarations.append(
            f"wire {width + ' ' if width else ''}{wire_name};"
        )
        if direction == "i":
            assignments.append(f"assign {wire_name} = {expression};")
        else:
            assignments.append(f"assign {expression} = {wire_name};")
        connections.append(f".{port:<32} ({wire_name})")
    formatted_connections = [
        f"    {item}{',' if index < len(connections) - 1 else ''}"
        for index, item in enumerate(connections)
    ]
    return "\n".join([
        "// Generated struct wrapper.",
        f'`include "{module.name}_typedef.sv"',
        "",
        f"module {module.name}_wrap #(",
        "    parameter integer CSR_AW = 32,",
        f"    parameter integer CSR_DW = {module.base_info.reg_bitwidth}",
        ")",
        "(",
        *_format_ports(ports),
        ");",
        "",
        "//localparam-----------------------------------------------------------------",
        "//signal declare-------------------------------------------------------------",
        *declarations,
        "//body-----------------------------------------------------------------------",
        "//output assign---",
        *assignments,
        "//statement----",
        "//instance----",
        f"{module.name} #(",
        "    .CSR_AW (CSR_AW),",
        "    .CSR_DW (CSR_DW)",
        f") u_{module.name}_{module.name} (",
        *formatted_connections,
        ");",
        "",
        "endmodule",
    ])


def _integration_template(module: ModuleModel) -> str:
    return "\n".join([
        "// Integration template for the generated CSR module.",
        f'`include "{module.name}_typedef.sv"',
        "",
        f"// Instantiate {module.name}_wrap when packed interfaces are preferred.",
        f"// Instantiate {module.name} when individual field ports are preferred.",
        "// Connect status and IRQ inputs from user RTL.",
        "// Connect cfg and cmd outputs to user RTL.",
    ])


def _targets(module: ModuleModel) -> list[RegisterModel]:
    return [
        reg for reg in module.registers if reg.reg_type in {"slave", "mem"}
    ]


def _deep_shadow(module: ModuleModel) -> int:
    return max(
        (reg.special.shadow for reg in module.registers),
        default=0,
    ) if any(reg.special.shadow >= 2 for reg in module.registers) else 0


def _present_groups(module: ModuleModel) -> list[str]:
    groups: list[str] = []
    types = {reg.reg_type for reg in module.registers}
    if "cfg" in types:
        groups.append("cfg")
    if "status" in types:
        groups.append("status")
    if "cmd" in types:
        groups.append("cmd")
    if "irq" in types:
        groups.extend(["irqsta", "irqclr"])
    return groups
